import { useState } from 'react'
import { ArrowRight, Check, Upload } from 'lucide-react'
import { categories } from '../data'

export default function PublishPage({ Layout, PageIntro }) {
  const [step, setStep] = useState(1)
  const [done, setDone] = useState(false)
  const [loading, setLoading] = useState(false)
  const next = event => { event.preventDefault(); if (step < 5) setStep(step + 1); else { setLoading(true); window.setTimeout(() => { setLoading(false); setDone(true) }, 500) } }
  return <Layout><main className="publish-page"><PageIntro eyebrow="PUBLISH WITH RTS" title="Your first step starts here." copy="Tell us about your book. We will help you find the right publishing path." />{done ? <div className="success-state"><Check size={44} /><h2>Enquiry received.</h2><p>Thank you. A publishing advisor will contact you within one working day.</p><a className="button" href="/">Back to home <ArrowRight size={16} /></a></div> : <form className="wizard" onSubmit={next}><div className="steps">{['You', 'Your book', 'Preferences', 'Manuscript', 'Review'].map((label, index) => <span className={index + 1 <= step ? 'current' : ''} key={label}><b>{index + 1}</b>{label}</span>)}</div><div className="wizard-panel">{step === 1 && <><h2>Tell us about yourself.</h2><div className="form-grid"><input required placeholder="Full name" /><input required type="email" placeholder="Email address" /><input required placeholder="Phone number" /><input placeholder="City & country" /></div></>}{step === 2 && <><h2>Tell us about your book.</h2><div className="form-grid"><input required placeholder="Book title" /><select required defaultValue=""><option value="" disabled>Choose a genre</option>{categories.map(item => <option key={item}>{item}</option>)}</select><select defaultValue="English"><option>English</option><option>Hindi</option><option>Other Indian language</option></select><input placeholder="Approximate word count" /></div></>}{step === 3 && <><h2>How would you like to publish?</h2><div className="check-grid">{['E-book', 'Paperback', 'Hardcover', 'Print-on-demand', 'Distribution', 'Marketing support'].map(item => <label key={item}><input type="checkbox" />{item}</label>)}</div></>}{step === 4 && <><h2>Share your manuscript.</h2><label className="upload-box"><Upload size={30} /><strong>Upload a manuscript</strong><span>PDF, DOC or DOCX up to 20MB</span><input type="file" accept=".pdf,.doc,.docx" /></label></>}{step === 5 && <><h2>Review your enquiry.</h2><p className="review-copy">Your information is ready to send. Our team will review your requirements and reply with a tailored recommendation.</p><label><input type="checkbox" required /> I agree to be contacted about my publishing enquiry.</label></>}<div className="wizard-actions">{step > 1 && <button type="button" className="text-button" onClick={() => setStep(step - 1)}>← Back</button>}<button className="button" type="submit" disabled={loading}>{loading ? 'Sending...' : step === 5 ? 'Submit enquiry' : 'Continue'}<ArrowRight size={16} /></button></div></div></form>}</main></Layout>
}
