import { ArrowRight, BookOpen, Check } from 'lucide-react'
import { usePackages, usePosts, useServices } from '../hooks'

export default function ContentPage({ Layout, PageIntro, title, eyebrow, copy, kind = 'standard' }) {
  const { data: services } = useServices()
  const { data: packages } = usePackages()
  const { data: posts } = usePosts()
  return <Layout><main className="standard-page"><PageIntro eyebrow={eyebrow} title={title} copy={copy} />{kind === 'services' && <div className="services-grid">{services.map((service, index) => <a href={`/services/${service.slug}`} className="service-card" key={service.id}><span>0{index + 1}</span><h2>{service.title}</h2><p>{service.description}</p><ArrowRight /></a>)}</div>}{kind === 'packages' && <div className="pricing-grid">{packages.map(item => <article className={`pricing-card ${item.tone}`} key={item.slug}>{item.popular && <span className="popular">MOST CHOSEN</span>}<span className="eyebrow">RTS {item.name.toUpperCase()}</span><h2>{item.name}</h2><strong>{item.price}</strong><p>Everything you need to publish with confidence.</p><ul>{item.features.map(feature => <li key={feature}><Check size={15} />{feature}</li>)}</ul><a className="button" href="/publish">Choose {item.name}<ArrowRight size={16} /></a></article>)}</div>}{kind === 'blog' && <div className="blog-grid">{posts.map(post => <a href={`/blog/${post.slug}`} className="post-card" key={post.id}><div style={{ background: post.color }}><BookOpen size={28} /></div><small>{post.category} · {post.date} · {post.time}</small><h3>{post.title}</h3><span>Read article <ArrowRight size={14} /></span></a>)}</div>}{kind === 'standard' && <div className="standard-content"><div><span className="eyebrow">THE RTS PROMISE</span><h2>Publishing with <em>purpose.</em></h2></div><div><p>{copy} Our team stays close, keeps the process transparent and gives every book the time it deserves.</p><a className="button" href="/publish">Start your journey<ArrowRight size={16} /></a></div></div>}</main></Layout>
}
